### PR TITLE
fixed

### LINKED ISSUE #105: debouncer resetting value
The debouncer is resetting values after each api calls

### PR DESCRIPTION
**Pull request by Chi-Chu319**
resolves #105

### CODE REVIEW

File: src/components/survey/reusables.tsx [hunk 1]
```diff
@@ -154,19 +154,18 @@ const Reusables: React.FC<Props> = ({ surveyId }) => {
    * 
    * @param updatedReusable updated reusable
    */
-  const onMaterialRowChange = async (newReusable: Reusable) => {
-    if (!keycloak?.token || !newReusable.id || !surveyId || newReusable.componentName === "") {
+  const onMaterialRowChange = async (updatedReusable: Reusable) => {
+    if (!keycloak?.token || !updatedReusable.id || !surveyId || updatedReusable.componentName === "") {
```
Comment (lauriLukkarinen) [inline src/components/survey/reusables.tsx:158]: Exclamation check should suffice in updatedReusable.componentName, since empty string is interpreted as "no value"
```suggestion
    if (!keycloak?.token || !updatedReusable.id || !surveyId || !updatedReusable.componentName) {
```

**Review by lauriLukkarinen — APPROVED** [review]
